import { BulletList, ContactCta, icons, PageHero } from "../components.jsx";
import { brand, processSteps, trustPoints } from "../content.js";

const { Circuitry, Microchip, ShieldCheck } = icons;

export default function AboutPage() {
  const breadcrumbs = [{ label: "Home", to: "/" }, { label: "About", to: "/about" }];
  return <main id="main-content" tabIndex="-1"><PageHero eyebrow="About Bloom Electronic" title="Founder-led electronics engineering support in Malaysia." copy="Bloom combines hardware, embedded firmware, connectivity and practical manufacturing preparation without presenting itself as a larger organisation than it is." breadcrumbs={breadcrumbs} />
    <section className="section"><div className="container about-page-grid"><div className="about-graphic" aria-hidden="true"><div className="about-chip"><Microchip weight="thin" /><span>BLOOM<br />ELECTRONIC</span></div><p>HARDWARE + FIRMWARE + MANUFACTURING</p></div><div className="about-page-copy"><p className="mini-label">How Bloom works</p><h2>Technical responsibility stays close to the customer problem.</h2><p>Clients communicate directly with {brand.founder.name}, founder and {brand.founder.title.toLowerCase()}. That keeps requirements, design decisions, prototype findings and manufacturing questions in one engineering context.</p><p>Bloom does not publish unsupported team size, certifications, office locations, customer identities or project outcomes.</p><BulletList items={trustPoints} /></div></div></section>
    <section className="section values-section"><div className="container"><div className="values-page-grid"><article><Circuitry /><h2>Engineering integrity</h2><p>Document what is known, what remains uncertain and what evidence is required next.</p></article><article><ShieldCheck /><h2>Confidential handling</h2><p>Keep customer identities and sensitive specifications out of public project summaries.</p></article><article><Microchip /><h2>Practical integration</h2><p>Consider circuitry, firmware, components, fabrication and bring-up as parts of one product system.</p></article></div></div></section>
    <section className="section"><div className="container"><div className="section-heading-row"><div><p className="eyebrow"><span />Development process</p><h2>Explicit stages and evidence gates.</h2></div></div><ol className="about-process">{processSteps.map(([number, title, copy]) => <li key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol></div></section>
    {(brand.founder.name || brand.phone || brand.linkedInUrl) && <section className="section verified-details"><div className="container detail-card-grid"><div><p className="eyebrow"><span />Founder and contact</p><h2>{brand.founder.name}</h2><p>{brand.founder.title}</p><p>{brand.founder.biography}</p></div><dl><div><dt>Business</dt><dd>{brand.publicName}</dd></div><div><dt>Service area</dt><dd>{brand.serviceArea}</dd></div><div><dt>WhatsApp / telephone</dt><dd><a href={`https://wa.me/${brand.phone.replace(/\D/g, "")}`} target="_blank" rel="noopener noreferrer">{brand.phone}</a></dd></div><div><dt>Professional profile</dt><dd><a href={brand.linkedInUrl} target="_blank" rel="noopener noreferrer">LinkedIn</a></dd></div></dl></div></section>}
    <ContactCta />
  </main>;
}
